stages:
    - client_build
    - api_deploy

before_script:
    - chmod 400 "$SSH_KEY"

variables:
    CLIENT_PATH: /var/www/prestige-estate/client
    API_PATH: /var/www/prestige-estate/api


Building_front:
    stage: client_build
    tags:
        - appointment
    script:
        - ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" root@ "
            cd '$CLIENT_PATH' &&
            git pull && 
            npm install &&
            npm run build &&
            service nginx restart"
    only:
        changes:
            - development
            - client/**/*

Deploying_api:
    stage: api_deploy
    tags:
        - appointment
    script:
        - ssh -o StrictHostKeyChecking=no -i "$SSH_KEY" root@ "
            cd '$API_PATH' &&
            git pull &&
            killall gunicorn &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            gunicorn --daemon --access-logfile /var/log/gunicorn.access.log --error-logfile /var/log/gunicorn.error.log appt_migration.wsgi:application &&
            service nginx restart "
    only:
        changes:
            - development
            - api/**/*